name: Flutter BDD
description: BBD Gherkin Test Framework using flutter-driver/Dart
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

# On Window machine:
# Flutter 1.22.5
# Dart 2.10.4

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  # dependency for running tests on Bitbar
  integration_test: ^1.0.1
  # the BDD bit
  flutter_gherkin: ^1.1.7
  path:
  glob:

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
